services:
  ispotify:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: kirill
      POSTGRES_PASSWORD: "123Kirill"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U kirill -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes: 
    db-data: